'use strict';
//
// RAN EP9 wire protocol — framing, garbage obfuscation, struct pack/unpack.
//
// All layout constants come from tools/layout-probe/layout.json, which is
// generated by compiling against the real SOURCE/ headers with MSVC. Nothing
// here is hand-computed: the probe exists precisely because hand-computing
// NET_MSG_LOBBY gives 2005 (a commented-out definition) instead of the live
// 1942, which would fail login with no useful error.
//
// Reference: SOURCE/Lib_Network/s_NetClient.cpp, RcvMsgBuffer.cpp
//

const fs = require('fs');
const path = require('path');

const LAYOUT_PATH = path.join(__dirname, '..', 'tools', 'layout-probe', 'layout.json');

function loadLayout() {
  if (!fs.existsSync(LAYOUT_PATH)) {
    throw new Error(
      `layout.json not found at ${LAYOUT_PATH}\n` +
      `Run: MOBILE/tools/layout-probe/build.cmd`
    );
  }
  const raw = fs.readFileSync(LAYOUT_PATH, 'utf8');
  // The probe emits a "_": null sentinel per struct to dodge trailing commas.
  const doc = JSON.parse(raw);
  for (const s of Object.values(doc.structs)) delete s.fields._;
  if (doc.loginFb) delete doc.loginFb._;
  if (doc.allEnums) delete doc.allEnums._;
  return doc;
}

const LAYOUT = loadLayout();
const { structs: S, enums: E, consts: C } = LAYOUT;
const LOGIN_FB = LAYOUT.loginFb || {};

// Reverse map for every enum member in s_NetGlobal.h, so an observed message ID
// always has a name. Several IDs share a value (different enums, same number),
// so this maps to a list rather than a single name.
const NAME_BY_VALUE = new Map();
for (const [name, value] of Object.entries(LAYOUT.allEnums || {})) {
  if (!NAME_BY_VALUE.has(value)) NAME_BY_VALUE.set(value, []);
  NAME_BY_VALUE.get(value).push(name);
}

// Prefer message-ish names when a value is ambiguous.
function nameOfType(t) {
  const all = NAME_BY_VALUE.get(t);
  if (!all || !all.length) return `UNKNOWN(${t})`;
  const msg = all.filter((n) => n.startsWith('NET_MSG_') ||
                                n.includes('_NET_MSG_'));
  const pick = msg.length ? msg : all;
  return pick.length > 1 ? `${pick[0]} [+${pick.length - 1} alias]` : pick[0];
}

const HEADER_SIZE = S.NET_MSG_GENERIC.size; // 8

// ---------------------------------------------------------------------------
// Garbage obfuscation
//
// SOURCE/Lib_Network/RcvMsgBuffer.cpp:10 — fixed table, not negotiated.
// SOURCE/Lib_Network/s_NetClient.cpp:856 GetGarbageMsg() — picks a random entry
// that differs from BOTH currently-held slots, stores it into slot[n], and
// SendMsgAddGarbageValue then toggles n between 0 and 1. Net effect: consecutive
// packets never carry the same filler string.
//
// Applied only once the connection leaves NET_STATE_LOGIN (s_NetClient.cpp:970).
// ---------------------------------------------------------------------------
const GARBAGE_DATA = ['K9IHANA', 'L8IDUL', 'M7HSET', 'N6GNET', 'O5FDASEOT'];

class Garbage {
  constructor() {
    this.slots = ['', ''];
    this.num = 0;
  }

  // Mirrors GetGarbageMsg() + the toggle in SendMsgAddGarbageValue().
  next() {
    let pick;
    do {
      pick = GARBAGE_DATA[Math.floor(Math.random() * GARBAGE_DATA.length)];
    } while (pick === this.slots[0] || pick === this.slots[1]);

    this.slots[this.num] = pick;
    const used = pick;
    this.num = (this.num + 1) % 2;
    return Buffer.from(used, 'latin1');
  }
}

// Receive side: identify and strip whichever filler the server used.
// Mirrors RcvMsgBuffer.cpp:179-192 (prefix match against the same table).
function stripGarbage(body) {
  for (const g of GARBAGE_DATA) {
    if (body.length >= g.length && body.toString('latin1', 0, g.length) === g) {
      return { garbage: g, body: body.subarray(g.length) };
    }
  }
  return { garbage: null, body };
}

// ---------------------------------------------------------------------------
// Framing
// ---------------------------------------------------------------------------

// Outbound safety guard.
//
// The server does not merely drop malformed packets — it BLOCKS THE SOURCE IP,
// and AddIPBlock() shells out to `netsh advfirewall firewall add rule` for a
// real Windows Firewall block (s_CIPFilter.cpp:126-152). The allow-list does
// NOT prevent this: AddIPBlock never consults m_setIPKnown.
//
// Triggers (s_CNetUser.cpp): buffer over NET_DATA_CLIENT_MSG_BUFSIZE (:492),
// unrecognised garbage (:528), and getMsg()==NULL with no garbage seen (:558).
// getMsg() returns NULL on the dwSize checks in RcvMsgBuffer.cpp:96-104.
//
// So we apply the SERVER'S OWN rules to our own output and refuse to transmit
// anything that would fail them. A bug becomes a local exception instead of a
// firewall ban on the developer's IP.
function assertSendable(wire, expectGarbage) {
  const size = wire.readUInt32LE(0);

  if (wire.length !== size) {
    throw new Error(`refusing to send: dwSize=${size} but buffer is ${wire.length}`);
  }
  if (size < HEADER_SIZE) {
    throw new Error(`refusing to send: dwSize=${size} < header ${HEADER_SIZE}`);
  }
  // RcvMsgBuffer.cpp:100 — dwSize > NET_DATA_BUFSIZE is rejected outright.
  if (size > C.NET_DATA_BUFSIZE) {
    throw new Error(
      `refusing to send: dwSize=${size} exceeds NET_DATA_BUFSIZE ${C.NET_DATA_BUFSIZE}`
    );
  }
  // Once past NET_STATE_LOGIN every packet must carry a recognised filler, or
  // CheckGarbageMsg blocks the IP.
  if (expectGarbage) {
    const body = wire.subarray(HEADER_SIZE);
    const { garbage } = stripGarbage(body);
    if (!garbage) {
      throw new Error('refusing to send: garbage layer active but no filler present');
    }
  }
  return wire;
}

// Build a wire packet. `body` excludes the 8-byte header.
// dwSize covers header + garbage + body (SendMsgAddGarbageValue bumps it).
function frame(msgType, body, garbage /* Garbage | null */) {
  const filler = garbage ? garbage.next() : Buffer.alloc(0);
  const total = HEADER_SIZE + filler.length + body.length;

  const out = Buffer.alloc(total);
  out.writeUInt32LE(total, 0);
  out.writeInt32LE(msgType, 4);
  filler.copy(out, HEADER_SIZE);
  body.copy(out, HEADER_SIZE + filler.length);

  return assertSendable(out, !!garbage);
}

// Pull complete packets out of a rolling receive buffer.
// Returns { packets: [{ type, size, body, garbage }], rest: Buffer }.
function parse(buf, expectGarbage) {
  const packets = [];
  let off = 0;

  while (buf.length - off >= HEADER_SIZE) {
    const size = buf.readUInt32LE(off);
    const type = buf.readInt32LE(off + 4);

    // Mirrors the sanity checks in RcvMsgBuffer.cpp:96-104. A bad size means the
    // stream is desynced; surfacing it is far better than silently resyncing.
    if (size < HEADER_SIZE || size > 0x40000) {
      throw new Error(
        `desync: implausible dwSize=${size} (type=${type}) at offset ${off}`
      );
    }
    if (buf.length - off < size) break; // partial packet, wait for more

    let body = buf.subarray(off + HEADER_SIZE, off + size);
    let garbage = null;
    if (expectGarbage) ({ garbage, body } = stripGarbage(body));

    packets.push({ type, size, body, garbage });
    off += size;
  }

  return { packets, rest: buf.subarray(off) };
}

// ---------------------------------------------------------------------------
// Struct helpers — offsets come from the probe, never from literals.
// ---------------------------------------------------------------------------

// Struct lookup resolves against the curated probe entries first, then the
// full codegen table (442 structs / 1546 members from s_NetGlobal.h and the
// GLMSG headers). Curated entries win because a few are deliberate mirrors of
// prefixes, e.g. SNETLOBBY_CHARJOIN_PREFIX, which stop short of the
// variable-length tail. Everything else is available by name without anyone
// hand-transcribing it.
const ALL = LAYOUT.allStructs || {};

function getStruct(name) {
  const def = S[name] || ALL[name];
  if (!def) throw new Error(`unknown struct ${name}`);
  return def;
}

function allocBody(structName) {
  // Body excludes the header, which frame() writes.
  return Buffer.alloc(getStruct(structName).size - HEADER_SIZE);
}

function fieldOff(structName, field) {
  const f = getStruct(structName).fields[field];
  if (!f) throw new Error(`unknown field ${structName}.${field}`);
  return f.off - HEADER_SIZE; // body-relative
}

function writeInt32(body, structName, field, value) {
  body.writeInt32LE(value, fieldOff(structName, field));
}

// Fixed-size NUL-padded char array, as MSVC lays it out.
function writeCharArray(body, structName, field, str) {
  const f = getStruct(structName).fields[field];
  const off = f.off - HEADER_SIZE;
  body.fill(0, off, off + f.size);
  const bytes = Buffer.from(str, 'latin1');
  if (bytes.length >= f.size) {
    throw new Error(`${structName}.${field}: "${str}" exceeds ${f.size - 1} chars`);
  }
  bytes.copy(body, off);
}

// Write pre-encoded bytes into a fixed-size field (e.g. a TEA-encrypted
// credential, which is no longer a NUL-terminated string).
function writeBytes(body, structName, field, bytes) {
  const f = getStruct(structName).fields[field];
  const off = f.off - HEADER_SIZE;
  if (bytes.length !== f.size) {
    throw new Error(
      `${structName}.${field}: expected ${f.size} bytes, got ${bytes.length}`
    );
  }
  bytes.copy(body, off);
}

module.exports = {
  LAYOUT, S, E, C, LOGIN_FB, ALL, getStruct,
  NAME_BY_VALUE, nameOfType,
  writeBytes,
  HEADER_SIZE,
  GARBAGE_DATA,
  Garbage,
  frame, parse, stripGarbage, assertSendable,
  allocBody, fieldOff, writeInt32, writeCharArray,
};
