// GENERATED by gen-d3d9-impl.js from SOURCE/Tik/DXInclude/d3d9.h — do not edit.
// Re-run:  node shim/d3d/gen-d3d9-impl.js
//
// One macro per interface, expanding to every method the interface declares.
// A shim class uses it and then overrides only what it really implements; the
// rest compile to harmless success. This keeps the vtables exactly in step with
// the SDK header no matter which methods get real bodies later.
#pragma once

// ---- IDirect3D9 (17 methods) ----
#define RAN_D3D9_STUBS_IDIRECT3D9 \
    HRESULT RegisterSoftwareDevice(void*) override { return D3D_OK; } \
    HRESULT CheckDeviceFormatConversion(UINT, D3DDEVTYPE, D3DFORMAT, D3DFORMAT) override { return D3D_OK; } \
    HMONITOR GetAdapterMonitor(UINT) override { return (HMONITOR)0; }

// ---- IDirect3DDevice9 (119 methods) ----
#define RAN_D3D9_STUBS_IDIRECT3DDEVICE9 \
    UINT GetAvailableTextureMem() override { return 0; } \
    HRESULT EvictManagedResources() override { return D3D_OK; } \
    HRESULT SetCursorProperties(UINT, UINT, IDirect3DSurface9*) override { return D3D_OK; } \
    void SetCursorPosition(int, int, DWORD) override { } \
    BOOL ShowCursor(BOOL) override { return FALSE; } \
    HRESULT GetSwapChain(UINT iSwapChain,IDirect3DSwapChain9** pSwapChain) override { if (pSwapChain) *pSwapChain = NULL; return D3DERR_NOTAVAILABLE; } \
    UINT GetNumberOfSwapChains() override { return 0; } \
    HRESULT GetRasterStatus(UINT, D3DRASTER_STATUS*) override { return D3D_OK; } \
    HRESULT SetDialogBoxMode(BOOL) override { return D3D_OK; } \
    void SetGammaRamp(UINT, DWORD, CONST D3DGAMMARAMP*) override { } \
    void GetGammaRamp(UINT, D3DGAMMARAMP*) override { } \
    HRESULT CreateVolumeTexture(UINT, UINT, UINT, UINT, DWORD, D3DFORMAT, D3DPOOL, IDirect3DVolumeTexture9**, HANDLE*) override { return D3D_OK; } \
    HRESULT CreateCubeTexture(UINT, UINT, DWORD, D3DFORMAT, D3DPOOL, IDirect3DCubeTexture9**, HANDLE*) override { return D3D_OK; } \
    HRESULT UpdateSurface(IDirect3DSurface9*, CONST RECT*, IDirect3DSurface9*, CONST POINT*) override { return D3D_OK; } \
    HRESULT UpdateTexture(IDirect3DBaseTexture9*, IDirect3DBaseTexture9*) override { return D3D_OK; } \
    HRESULT GetRenderTargetData(IDirect3DSurface9*, IDirect3DSurface9*) override { return D3D_OK; } \
    HRESULT GetFrontBufferData(UINT, IDirect3DSurface9*) override { return D3D_OK; } \
    HRESULT ColorFill(IDirect3DSurface9*, CONST RECT*, D3DCOLOR) override { return D3D_OK; } \
    HRESULT GetClipPlane(DWORD, float*) override { return D3D_OK; } \
    HRESULT CreateStateBlock(D3DSTATEBLOCKTYPE Type,IDirect3DStateBlock9** ppSB) override { if (ppSB) *ppSB = NULL; return D3DERR_NOTAVAILABLE; } \
    HRESULT SetClipStatus(CONST D3DCLIPSTATUS9*) override { return D3D_OK; } \
    HRESULT GetClipStatus(D3DCLIPSTATUS9*) override { return D3D_OK; } \
    HRESULT ValidateDevice(DWORD*) override { return D3D_OK; } \
    HRESULT SetPaletteEntries(UINT, CONST PALETTEENTRY*) override { return D3D_OK; } \
    HRESULT GetPaletteEntries(UINT, PALETTEENTRY*) override { return D3D_OK; } \
    HRESULT SetCurrentTexturePalette(UINT) override { return D3D_OK; } \
    HRESULT GetCurrentTexturePalette(UINT *PaletteNumber) override { return D3D_OK; } \
    HRESULT SetScissorRect(CONST RECT*) override { return D3D_OK; } \
    HRESULT GetScissorRect(RECT*) override { return D3D_OK; } \
    HRESULT SetSoftwareVertexProcessing(BOOL) override { return D3D_OK; } \
    BOOL GetSoftwareVertexProcessing() override { return FALSE; } \
    HRESULT SetNPatchMode(float) override { return D3D_OK; } \
    float GetNPatchMode() override { return 0.0f; } \
    HRESULT ProcessVertices(UINT, UINT, UINT, IDirect3DVertexBuffer9*, IDirect3DVertexDeclaration9*, DWORD) override { return D3D_OK; } \
    HRESULT CreateVertexDeclaration(CONST D3DVERTEXELEMENT9* pVertexElements,IDirect3DVertexDeclaration9** ppDecl) override { if (ppDecl) *ppDecl = NULL; return D3DERR_NOTAVAILABLE; } \
    HRESULT SetVertexDeclaration(IDirect3DVertexDeclaration9*) override { return D3D_OK; } \
    HRESULT GetVertexDeclaration(IDirect3DVertexDeclaration9** ppDecl) override { if (ppDecl) *ppDecl = NULL; return D3DERR_NOTAVAILABLE; } \
    HRESULT CreateVertexShader(CONST DWORD* pFunction,IDirect3DVertexShader9** ppShader) override { if (ppShader) *ppShader = NULL; return D3DERR_NOTAVAILABLE; } \
    HRESULT SetVertexShader(IDirect3DVertexShader9*) override { return D3D_OK; } \
    HRESULT GetVertexShader(IDirect3DVertexShader9** ppShader) override { if (ppShader) *ppShader = NULL; return D3DERR_NOTAVAILABLE; } \
    HRESULT SetVertexShaderConstantF(UINT, CONST float*, UINT) override { return D3D_OK; } \
    HRESULT GetVertexShaderConstantF(UINT, float*, UINT) override { return D3D_OK; } \
    HRESULT SetVertexShaderConstantI(UINT, CONST int*, UINT) override { return D3D_OK; } \
    HRESULT GetVertexShaderConstantI(UINT, int*, UINT) override { return D3D_OK; } \
    HRESULT SetVertexShaderConstantB(UINT, CONST BOOL*, UINT) override { return D3D_OK; } \
    HRESULT GetVertexShaderConstantB(UINT, BOOL*, UINT) override { return D3D_OK; } \
    HRESULT GetStreamSource(UINT, IDirect3DVertexBuffer9**, UINT*, UINT*) override { return D3D_OK; } \
    HRESULT SetStreamSourceFreq(UINT, UINT) override { return D3D_OK; } \
    HRESULT GetStreamSourceFreq(UINT, UINT*) override { return D3D_OK; } \
    HRESULT GetIndices(IDirect3DIndexBuffer9** ppIndexData) override { if (ppIndexData) *ppIndexData = NULL; return D3DERR_NOTAVAILABLE; } \
    HRESULT CreatePixelShader(CONST DWORD* pFunction,IDirect3DPixelShader9** ppShader) override { if (ppShader) *ppShader = NULL; return D3DERR_NOTAVAILABLE; } \
    HRESULT SetPixelShader(IDirect3DPixelShader9*) override { return D3D_OK; } \
    HRESULT GetPixelShader(IDirect3DPixelShader9** ppShader) override { if (ppShader) *ppShader = NULL; return D3DERR_NOTAVAILABLE; } \
    HRESULT SetPixelShaderConstantF(UINT, CONST float*, UINT) override { return D3D_OK; } \
    HRESULT GetPixelShaderConstantF(UINT, float*, UINT) override { return D3D_OK; } \
    HRESULT SetPixelShaderConstantI(UINT, CONST int*, UINT) override { return D3D_OK; } \
    HRESULT GetPixelShaderConstantI(UINT, int*, UINT) override { return D3D_OK; } \
    HRESULT SetPixelShaderConstantB(UINT, CONST BOOL*, UINT) override { return D3D_OK; } \
    HRESULT GetPixelShaderConstantB(UINT, BOOL*, UINT) override { return D3D_OK; } \
    HRESULT DrawRectPatch(UINT, CONST float*, CONST D3DRECTPATCH_INFO*) override { return D3D_OK; } \
    HRESULT DrawTriPatch(UINT, CONST float*, CONST D3DTRIPATCH_INFO*) override { return D3D_OK; } \
    HRESULT DeletePatch(UINT) override { return D3D_OK; } \
    HRESULT CreateQuery(D3DQUERYTYPE Type,IDirect3DQuery9** ppQuery) override { if (ppQuery) *ppQuery = NULL; return D3DERR_NOTAVAILABLE; }

// ---- IDirect3DResource9 (11 methods) ----
#define RAN_D3D9_STUBS_IDIRECT3DRESOURCE9 \
    HRESULT QueryInterface(REFIID, void**) override { return D3D_OK; } \
    ULONG AddRef() override { return 1; } \
    ULONG Release() override { return 1; } \
    HRESULT GetDevice(IDirect3DDevice9** ppDevice) override { if (ppDevice) *ppDevice = NULL; return D3DERR_NOTAVAILABLE; } \
    HRESULT SetPrivateData(REFGUID, CONST void*, DWORD, DWORD) override { return D3D_OK; } \
    HRESULT GetPrivateData(REFGUID, void*, DWORD*) override { return D3D_OK; } \
    HRESULT FreePrivateData(REFGUID) override { return D3D_OK; } \
    DWORD SetPriority(DWORD) override { return 0; } \
    DWORD GetPriority() override { return 0; } \
    void PreLoad() override { } \
    D3DRESOURCETYPE GetType() override { return (D3DRESOURCETYPE)0; }

// ---- IDirect3DBaseTexture9 (17 methods) ----
#define RAN_D3D9_STUBS_IDIRECT3DBASETEXTURE9 \
    HRESULT QueryInterface(REFIID, void**) override { return D3D_OK; } \
    ULONG AddRef() override { return 1; } \
    ULONG Release() override { return 1; } \
    HRESULT GetDevice(IDirect3DDevice9** ppDevice) override { if (ppDevice) *ppDevice = NULL; return D3DERR_NOTAVAILABLE; } \
    HRESULT SetPrivateData(REFGUID, CONST void*, DWORD, DWORD) override { return D3D_OK; } \
    HRESULT GetPrivateData(REFGUID, void*, DWORD*) override { return D3D_OK; } \
    HRESULT FreePrivateData(REFGUID) override { return D3D_OK; } \
    DWORD SetPriority(DWORD) override { return 0; } \
    DWORD GetPriority() override { return 0; } \
    void PreLoad() override { } \
    D3DRESOURCETYPE GetType() override { return (D3DRESOURCETYPE)0; } \
    DWORD SetLOD(DWORD) override { return 0; } \
    DWORD GetLOD() override { return 0; } \
    DWORD GetLevelCount() override { return 0; } \
    HRESULT SetAutoGenFilterType(D3DTEXTUREFILTERTYPE) override { return D3D_OK; } \
    D3DTEXTUREFILTERTYPE GetAutoGenFilterType() override { return (D3DTEXTUREFILTERTYPE)0; } \
    void GenerateMipSubLevels() override { }

// ---- IDirect3DTexture9 (22 methods) ----
#define RAN_D3D9_STUBS_IDIRECT3DTEXTURE9 \
    HRESULT GetDevice(IDirect3DDevice9** ppDevice) override { if (ppDevice) *ppDevice = NULL; return D3DERR_NOTAVAILABLE; } \
    HRESULT SetPrivateData(REFGUID, CONST void*, DWORD, DWORD) override { return D3D_OK; } \
    HRESULT GetPrivateData(REFGUID, void*, DWORD*) override { return D3D_OK; } \
    HRESULT FreePrivateData(REFGUID) override { return D3D_OK; } \
    DWORD SetPriority(DWORD) override { return 0; } \
    DWORD GetPriority() override { return 0; } \
    void PreLoad() override { } \
    D3DRESOURCETYPE GetType() override { return (D3DRESOURCETYPE)0; } \
    DWORD SetLOD(DWORD) override { return 0; } \
    DWORD GetLOD() override { return 0; } \
    HRESULT SetAutoGenFilterType(D3DTEXTUREFILTERTYPE) override { return D3D_OK; } \
    D3DTEXTUREFILTERTYPE GetAutoGenFilterType() override { return (D3DTEXTUREFILTERTYPE)0; } \
    void GenerateMipSubLevels() override { } \
    HRESULT AddDirtyRect(CONST RECT*) override { return D3D_OK; }

// ---- IDirect3DCubeTexture9 (22 methods) ----
#define RAN_D3D9_STUBS_IDIRECT3DCUBETEXTURE9 \
    HRESULT GetDevice(IDirect3DDevice9** ppDevice) override { if (ppDevice) *ppDevice = NULL; return D3DERR_NOTAVAILABLE; } \
    HRESULT SetPrivateData(REFGUID, CONST void*, DWORD, DWORD) override { return D3D_OK; } \
    HRESULT GetPrivateData(REFGUID, void*, DWORD*) override { return D3D_OK; } \
    HRESULT FreePrivateData(REFGUID) override { return D3D_OK; } \
    DWORD SetPriority(DWORD) override { return 0; } \
    DWORD GetPriority() override { return 0; } \
    void PreLoad() override { } \
    DWORD SetLOD(DWORD) override { return 0; } \
    DWORD GetLOD() override { return 0; } \
    HRESULT SetAutoGenFilterType(D3DTEXTUREFILTERTYPE) override { return D3D_OK; } \
    D3DTEXTUREFILTERTYPE GetAutoGenFilterType() override { return (D3DTEXTUREFILTERTYPE)0; } \
    void GenerateMipSubLevels() override { } \
    HRESULT GetCubeMapSurface(D3DCUBEMAP_FACES FaceType,UINT Level,IDirect3DSurface9** ppCubeMapSurface) override { if (ppCubeMapSurface) *ppCubeMapSurface = NULL; return D3DERR_NOTAVAILABLE; } \
    HRESULT LockRect(D3DCUBEMAP_FACES, UINT, D3DLOCKED_RECT*, CONST RECT*, DWORD) override { return D3D_OK; } \
    HRESULT UnlockRect(D3DCUBEMAP_FACES, UINT) override { return D3D_OK; } \
    HRESULT AddDirtyRect(D3DCUBEMAP_FACES, CONST RECT*) override { return D3D_OK; }

// ---- IDirect3DVolumeTexture9 (22 methods) ----
#define RAN_D3D9_STUBS_IDIRECT3DVOLUMETEXTURE9 \
    HRESULT QueryInterface(REFIID, void**) override { return D3D_OK; } \
    ULONG AddRef() override { return 1; } \
    ULONG Release() override { return 1; } \
    HRESULT GetDevice(IDirect3DDevice9** ppDevice) override { if (ppDevice) *ppDevice = NULL; return D3DERR_NOTAVAILABLE; } \
    HRESULT SetPrivateData(REFGUID, CONST void*, DWORD, DWORD) override { return D3D_OK; } \
    HRESULT GetPrivateData(REFGUID, void*, DWORD*) override { return D3D_OK; } \
    HRESULT FreePrivateData(REFGUID) override { return D3D_OK; } \
    DWORD SetPriority(DWORD) override { return 0; } \
    DWORD GetPriority() override { return 0; } \
    void PreLoad() override { } \
    D3DRESOURCETYPE GetType() override { return (D3DRESOURCETYPE)0; } \
    DWORD SetLOD(DWORD) override { return 0; } \
    DWORD GetLOD() override { return 0; } \
    DWORD GetLevelCount() override { return 0; } \
    HRESULT SetAutoGenFilterType(D3DTEXTUREFILTERTYPE) override { return D3D_OK; } \
    D3DTEXTUREFILTERTYPE GetAutoGenFilterType() override { return (D3DTEXTUREFILTERTYPE)0; } \
    void GenerateMipSubLevels() override { } \
    HRESULT GetLevelDesc(UINT, D3DVOLUME_DESC *pDesc) override { return D3D_OK; } \
    HRESULT GetVolumeLevel(UINT Level,IDirect3DVolume9** ppVolumeLevel) override { if (ppVolumeLevel) *ppVolumeLevel = NULL; return D3DERR_NOTAVAILABLE; } \
    HRESULT LockBox(UINT, D3DLOCKED_BOX*, CONST D3DBOX*, DWORD) override { return D3D_OK; } \
    HRESULT UnlockBox(UINT) override { return D3D_OK; } \
    HRESULT AddDirtyBox(CONST D3DBOX*) override { return D3D_OK; }

// ---- IDirect3DSurface9 (17 methods) ----
#define RAN_D3D9_STUBS_IDIRECT3DSURFACE9 \
    HRESULT GetDevice(IDirect3DDevice9** ppDevice) override { if (ppDevice) *ppDevice = NULL; return D3DERR_NOTAVAILABLE; } \
    HRESULT SetPrivateData(REFGUID, CONST void*, DWORD, DWORD) override { return D3D_OK; } \
    HRESULT GetPrivateData(REFGUID, void*, DWORD*) override { return D3D_OK; } \
    HRESULT FreePrivateData(REFGUID) override { return D3D_OK; } \
    DWORD SetPriority(DWORD) override { return 0; } \
    DWORD GetPriority() override { return 0; } \
    void PreLoad() override { } \
    D3DRESOURCETYPE GetType() override { return (D3DRESOURCETYPE)0; } \
    HRESULT GetContainer(REFIID, void**) override { return D3D_OK; } \
    HRESULT GetDC(HDC *phdc) override { return D3D_OK; } \
    HRESULT ReleaseDC(HDC) override { return D3D_OK; }

// ---- IDirect3DVolume9 (11 methods) ----
#define RAN_D3D9_STUBS_IDIRECT3DVOLUME9 \
    HRESULT QueryInterface(REFIID, void**) override { return D3D_OK; } \
    ULONG AddRef() override { return 1; } \
    ULONG Release() override { return 1; } \
    HRESULT GetDevice(IDirect3DDevice9** ppDevice) override { if (ppDevice) *ppDevice = NULL; return D3DERR_NOTAVAILABLE; } \
    HRESULT SetPrivateData(REFGUID, CONST void*, DWORD, DWORD) override { return D3D_OK; } \
    HRESULT GetPrivateData(REFGUID, void*, DWORD*) override { return D3D_OK; } \
    HRESULT FreePrivateData(REFGUID) override { return D3D_OK; } \
    HRESULT GetContainer(REFIID, void**) override { return D3D_OK; } \
    HRESULT GetDesc(D3DVOLUME_DESC *pDesc) override { return D3D_OK; } \
    HRESULT LockBox(D3DLOCKED_BOX *, CONST D3DBOX*, DWORD) override { return D3D_OK; } \
    HRESULT UnlockBox() override { return D3D_OK; }

// ---- IDirect3DVertexBuffer9 (14 methods) ----
#define RAN_D3D9_STUBS_IDIRECT3DVERTEXBUFFER9 \
    HRESULT GetDevice(IDirect3DDevice9** ppDevice) override { if (ppDevice) *ppDevice = NULL; return D3DERR_NOTAVAILABLE; } \
    HRESULT SetPrivateData(REFGUID, CONST void*, DWORD, DWORD) override { return D3D_OK; } \
    HRESULT GetPrivateData(REFGUID, void*, DWORD*) override { return D3D_OK; } \
    HRESULT FreePrivateData(REFGUID) override { return D3D_OK; } \
    DWORD SetPriority(DWORD) override { return 0; } \
    DWORD GetPriority() override { return 0; } \
    void PreLoad() override { } \
    D3DRESOURCETYPE GetType() override { return (D3DRESOURCETYPE)0; }

// ---- IDirect3DIndexBuffer9 (14 methods) ----
#define RAN_D3D9_STUBS_IDIRECT3DINDEXBUFFER9 \
    HRESULT GetDevice(IDirect3DDevice9** ppDevice) override { if (ppDevice) *ppDevice = NULL; return D3DERR_NOTAVAILABLE; } \
    HRESULT SetPrivateData(REFGUID, CONST void*, DWORD, DWORD) override { return D3D_OK; } \
    HRESULT GetPrivateData(REFGUID, void*, DWORD*) override { return D3D_OK; } \
    HRESULT FreePrivateData(REFGUID) override { return D3D_OK; } \
    DWORD SetPriority(DWORD) override { return 0; } \
    DWORD GetPriority() override { return 0; } \
    void PreLoad() override { } \
    D3DRESOURCETYPE GetType() override { return (D3DRESOURCETYPE)0; }

// ---- IDirect3DStateBlock9 (6 methods) ----
#define RAN_D3D9_STUBS_IDIRECT3DSTATEBLOCK9 \
    HRESULT GetDevice(IDirect3DDevice9** ppDevice) override { if (ppDevice) *ppDevice = NULL; return D3DERR_NOTAVAILABLE; }

// ---- IDirect3DSwapChain9 (10 methods) ----
#define RAN_D3D9_STUBS_IDIRECT3DSWAPCHAIN9 \
    HRESULT QueryInterface(REFIID, void**) override { return D3D_OK; } \
    ULONG AddRef() override { return 1; } \
    ULONG Release() override { return 1; } \
    HRESULT Present(CONST RECT*, CONST RECT*, HWND, CONST RGNDATA*, DWORD) override { return D3D_OK; } \
    HRESULT GetFrontBufferData(IDirect3DSurface9*) override { return D3D_OK; } \
    HRESULT GetBackBuffer(UINT iBackBuffer,D3DBACKBUFFER_TYPE Type,IDirect3DSurface9** ppBackBuffer) override { if (ppBackBuffer) *ppBackBuffer = NULL; return D3DERR_NOTAVAILABLE; } \
    HRESULT GetRasterStatus(D3DRASTER_STATUS*) override { return D3D_OK; } \
    HRESULT GetDisplayMode(D3DDISPLAYMODE*) override { return D3D_OK; } \
    HRESULT GetDevice(IDirect3DDevice9** ppDevice) override { if (ppDevice) *ppDevice = NULL; return D3DERR_NOTAVAILABLE; } \
    HRESULT GetPresentParameters(D3DPRESENT_PARAMETERS*) override { return D3D_OK; }

// ---- IDirect3DVertexDeclaration9 (5 methods) ----
#define RAN_D3D9_STUBS_IDIRECT3DVERTEXDECLARATION9 \
    HRESULT QueryInterface(REFIID, void**) override { return D3D_OK; } \
    ULONG AddRef() override { return 1; } \
    ULONG Release() override { return 1; } \
    HRESULT GetDevice(IDirect3DDevice9** ppDevice) override { if (ppDevice) *ppDevice = NULL; return D3DERR_NOTAVAILABLE; } \
    HRESULT GetDeclaration(D3DVERTEXELEMENT9*, UINT*) override { return D3D_OK; }

// ---- IDirect3DVertexShader9 (5 methods) ----
#define RAN_D3D9_STUBS_IDIRECT3DVERTEXSHADER9 \
    HRESULT QueryInterface(REFIID, void**) override { return D3D_OK; } \
    ULONG AddRef() override { return 1; } \
    ULONG Release() override { return 1; } \
    HRESULT GetDevice(IDirect3DDevice9** ppDevice) override { if (ppDevice) *ppDevice = NULL; return D3DERR_NOTAVAILABLE; } \
    HRESULT GetFunction(void*, UINT*) override { return D3D_OK; }

// ---- IDirect3DPixelShader9 (5 methods) ----
#define RAN_D3D9_STUBS_IDIRECT3DPIXELSHADER9 \
    HRESULT QueryInterface(REFIID, void**) override { return D3D_OK; } \
    ULONG AddRef() override { return 1; } \
    ULONG Release() override { return 1; } \
    HRESULT GetDevice(IDirect3DDevice9** ppDevice) override { if (ppDevice) *ppDevice = NULL; return D3DERR_NOTAVAILABLE; } \
    HRESULT GetFunction(void*, UINT*) override { return D3D_OK; }

// ---- IDirect3DQuery9 (8 methods) ----
#define RAN_D3D9_STUBS_IDIRECT3DQUERY9 \
    HRESULT QueryInterface(REFIID, void**) override { return D3D_OK; } \
    ULONG AddRef() override { return 1; } \
    ULONG Release() override { return 1; } \
    HRESULT GetDevice(IDirect3DDevice9** ppDevice) override { if (ppDevice) *ppDevice = NULL; return D3DERR_NOTAVAILABLE; } \
    D3DQUERYTYPE GetType() override { return (D3DQUERYTYPE)0; } \
    DWORD GetDataSize() override { return 0; } \
    HRESULT Issue(DWORD) override { return D3D_OK; } \
    HRESULT GetData(void*, DWORD, DWORD) override { return D3D_OK; }

