'use strict';
//
// Self-healing build loop for the struct codegen.
//
// Not every declaration in s_NetGlobal.h can be measured: some members have
// incomplete types in this translation unit, some structs are non-standard-
// layout, and offsetof is invalid on a few. Rather than hand-maintaining a
// blacklist (which would rot the moment the headers change), this compiles,
// reads the COMPILER'S diagnostics, maps each error back to the exact
// DUMP_MEMBER/DUMP_STRUCT line that produced it, records that in exclude.txt,
// regenerates and tries again until the build is clean.
//
// The blacklist is therefore derived from the compiler, like everything else
// here. Run it after any header change:
//
//   node build-structs.js
//

const { execFileSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const DIR = __dirname;
const INC = path.join(DIR, 'structs.gen.inc');
const EXCLUDE_FILE = path.join(DIR, 'exclude.txt');
const MAX_ROUNDS = 40;

function readExcludes() {
  if (!fs.existsSync(EXCLUDE_FILE)) return new Set();
  return new Set(
    fs.readFileSync(EXCLUDE_FILE, 'utf8')
      .split('\n').map((l) => l.split('#')[0].trim()).filter(Boolean)
  );
}

function writeExcludes(set) {
  const body = [
    '# GENERATED by build-structs.js from compiler diagnostics — do not hand-edit.',
    '# Each entry is a struct or Struct.member that cannot be measured with',
    '# offsetof/sizeof in the probe translation unit.',
    ...[...set].sort(),
  ].join('\n');
  fs.writeFileSync(EXCLUDE_FILE, body + '\n');
}

function generate() {
  const out = execFileSync(process.execPath, [path.join(DIR, 'gen-structs.js')],
                           { encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 });
  fs.writeFileSync(INC, out);
  const m = out.match(/\/\/ (\d+) structs, (\d+) members/);
  return m ? { structs: +m[1], members: +m[2] } : { structs: 0, members: 0 };
}

function compile() {
  try {
    execFileSync(process.env.ComSpec || 'cmd.exe',
                 ['/c', path.join(DIR, 'build.cmd')],
                 { encoding: 'utf8', cwd: DIR, maxBuffer: 64 * 1024 * 1024 });
    return null;
  } catch (err) {
    return `${err.stdout || ''}\n${err.stderr || ''}`;
  }
}

// Map "structs.gen.inc(N): error ..." back to the identifiers on line N.
function offendersFrom(output) {
  const lines = fs.readFileSync(INC, 'utf8').split('\n');
  const bad = new Set();
  const re = /structs\.gen\.inc\((\d+)\)\s*:\s*(?:fatal\s+)?error/gi;
  let m;
  while ((m = re.exec(output)) !== null) {
    const src = lines[Number(m[1]) - 1] || '';
    // Names may be namespace-qualified (GLMSG::SNETPC_GOTO), so allow ':'.
    let d = src.match(/DUMP_MEMBER\(\s*([\w:]+)\s*,\s*(\w+)\s*\)/);
    if (d) { bad.add(`${d[1]}.${d[2]}`); continue; }
    d = src.match(/DUMP_STRUCT\(\s*([\w:]+)\s*\)/);
    if (d) bad.add(d[1]);
  }
  return bad;
}

let excludes = readExcludes();
for (let round = 1; round <= MAX_ROUNDS; round++) {
  const stats = generate();
  process.stdout.write(
    `round ${round}: ${stats.structs} structs / ${stats.members} members, ` +
    `${excludes.size} excluded ... `);

  const err = compile();
  if (!err) {
    console.log('BUILD OK');
    writeExcludes(excludes);
    process.exit(0);
  }

  const bad = offendersFrom(err);
  if (!bad.size) {
    console.log('FAILED with errors not attributable to structs.gen.inc');
    console.log(err.split('\n').filter((l) => /error/i.test(l)).slice(0, 15).join('\n'));
    process.exit(1);
  }

  console.log(`excluding ${bad.size}`);
  for (const b of bad) excludes.add(b);
  writeExcludes(excludes);
}

console.log(`did not converge in ${MAX_ROUNDS} rounds`);
process.exit(1);
