// GENERATED by gen-effectprops.js — do not edit.
// Verbatim copies of the file-scope PROPERTY_10x structs declared in
// DxEffect/Single/*PROP.cpp, which no header exposes. Wrapped in a namespace
// each, because every one of these files names its oldest struct PROPERTY_100.
#pragma once
namespace EFFLEGACY_MESH {
struct PROPERTY_100
{
	DWORD		m_dwFlag;

	char		m_szMeshFile[256];
	char		m_szMeshFile1[256];
	char		m_szMeshFile2[256];
	int			m_nRotationType;
	int			m_nBlend;

	float		m_fMorphRoopNum;

	float		m_fSizeRate1;
	float		m_fSizeRate2;

	float		m_fSizeStart;
	float		m_fSizeMid1;
	float		m_fSizeMid2;
	float		m_fSizeEnd;	

	float		m_fAlphaRate1;
	float		m_fAlphaRate2;

	float		m_fAlphaStart;
	float		m_fAlphaMid1;
	float		m_fAlphaMid2;
	float		m_fAlphaEnd;
		
	float		m_fRotationAngle;
	float		m_fRotationVelocity;

	float		m_fTexRotateAngel;
	int			m_nTexRotateType;
	D3DXVECTOR3	m_vTexCenter;
	
	D3DXVECTOR3	m_vTexVel;

	float		m_fTexScaleStart;
	float		m_fTexScaleEnd;

	float       m_fMaterial[4]; // Note : 4
	float       m_fMaterialRatio0; // Note : 0
	float       m_fMaterialRatio1; // Note : 1
	
	D3DXCOLOR	m_clrStart;
	D3DXCOLOR	m_clrEnd;

	PROPERTY_100()
	{
		memset( m_szMeshFile, 0, sizeof(char)*256 );
		memset( m_szMeshFile1, 0, sizeof(char)*256 );
		memset( m_szMeshFile2, 0, sizeof(char)*256 );
	};
};
struct PROPERTY_101				// Ver. 101
{
	DWORD		m_dwFlag;

	int			m_nBlurObject; // Note : Ver.101

	char		m_szMeshFile[256];
	char		m_szMeshFile1[256];
	char		m_szMeshFile2[256];
	int			m_nRotationType;
	int			m_nBlend;

	float		m_fMorphRoopNum;

	float		m_fSizeRate1;
	float		m_fSizeRate2;

	float		m_fSizeStart;
	float		m_fSizeMid1;
	float		m_fSizeMid2;
	float		m_fSizeEnd;	

	float		m_fAlphaRate1;
	float		m_fAlphaRate2;

	float		m_fAlphaStart;
	float		m_fAlphaMid1;
	float		m_fAlphaMid2;
	float		m_fAlphaEnd;
		
	float		m_fRotationAngle;
	float		m_fRotationVelocity;

	float		m_fTexRotateAngel;
	int			m_nTexRotateType;
	D3DXVECTOR3	m_vTexCenter;
	
	D3DXVECTOR3	m_vTexVel;

	float		m_fTexScaleStart;
	float		m_fTexScaleEnd;

	float       m_fMaterial[4]; // Note : 4
	float       m_fMaterialRatio0; // Note : 0
	float       m_fMaterialRatio1; // Note : 1
	
	D3DXCOLOR	m_clrStart;
	D3DXCOLOR	m_clrEnd;

	PROPERTY_101()
	{
		memset( m_szMeshFile, 0, sizeof(char)*256 );
		memset( m_szMeshFile1, 0, sizeof(char)*256 );
		memset( m_szMeshFile2, 0, sizeof(char)*256 );
	};
};
struct PROPERTY_102				// Ver. 102
{
	DWORD		m_dwFlag;

	int			m_nBlurObject; // Note : Ver.101

	int			m_nCol; // Ver.102
	int			m_nRow; // Ver.102
	float		m_fAniTime; // Ver.102

	char		m_szMeshFile[256];
	char		m_szMeshFile1[256];
	char		m_szMeshFile2[256];
	char		m_szTexture[256]; //	Note: Ver.102
	int			m_nRotationType;
	int			m_nBlend;

	float		m_fMorphRoopNum;

	float		m_fSizeRate1;
	float		m_fSizeRate2;

	float		m_fSizeStart;
	float		m_fSizeMid1;
	float		m_fSizeMid2;
	float		m_fSizeEnd;	

	float		m_fAlphaRate1;
	float		m_fAlphaRate2;

	float		m_fAlphaStart;
	float		m_fAlphaMid1;
	float		m_fAlphaMid2;
	float		m_fAlphaEnd;
		
	float		m_fRotationAngle;
	float		m_fRotationVelocity;

	float		m_fTexRotateAngel;
	int			m_nTexRotateType;
	D3DXVECTOR3	m_vTexCenter;
	
	D3DXVECTOR3	m_vTexVel;

	float		m_fTexScaleStart;
	float		m_fTexScaleEnd;

	float       m_fMaterial[4]; // Note : 4
	float       m_fMaterialRatio0; // Note : 0
	float       m_fMaterialRatio1; // Note : 1
	
	D3DXCOLOR	m_clrStart;
	D3DXCOLOR	m_clrEnd;

	PROPERTY_102()
	{
		memset( m_szMeshFile, 0, sizeof(char)*256 );
		memset( m_szMeshFile1, 0, sizeof(char)*256 );
		memset( m_szMeshFile2, 0, sizeof(char)*256 );
		memset( m_szTexture, 0, sizeof(char)*256 );
	};
};
struct PROPERTY_103				// Ver. 103
{
	DWORD		m_dwFlag;

	int			m_nBlurObject; // Note : Ver.101

	int			m_nCol; // Ver.102
	int			m_nRow; // Ver.102
	float		m_fAniTime; // Ver.102

	char		m_szMeshFile[256];
	char		m_szMeshFile1[256];
	char		m_szMeshFile2[256];
	char		m_szTexture[256]; //	Note: Ver.102
	int			m_nRotationType;
	int			m_nBlend;

	float		m_fMorphRoopNum;

	float		m_fSizeRate1;
	float		m_fSizeRate2;

	float		m_fSizeStart;
	float		m_fSizeMid1;
	float		m_fSizeMid2;
	float		m_fSizeEnd;	

	D3DXVECTOR3	m_vSizeXYZ; // Note : XYZ ~! Ver.103

	float		m_fAlphaRate1;
	float		m_fAlphaRate2;

	float		m_fAlphaStart;
	float		m_fAlphaMid1;
	float		m_fAlphaMid2;
	float		m_fAlphaEnd;

	D3DXVECTOR2	m_vHeight; // x y
		
	float		m_fRotationAngle;

	float		m_fTexRotateAngel;
	int			m_nTexRotateType;
	D3DXVECTOR3	m_vTexCenter;
	
	D3DXVECTOR3	m_vTexVel;

	float		m_fTexScaleStart;
	float		m_fTexScaleEnd;

	float       m_fMaterial[4]; // Note : 4
	float       m_fMaterialRatio0; // Note : 0
	float       m_fMaterialRatio1; // Note : 1
	
	D3DXCOLOR	m_clrStart;
	D3DXCOLOR	m_clrEnd;

	PROPERTY_103()
	{
		memset( m_szMeshFile, 0, sizeof(char)*256 );
		memset( m_szMeshFile1, 0, sizeof(char)*256 );
		memset( m_szMeshFile2, 0, sizeof(char)*256 );
		memset( m_szTexture, 0, sizeof(char)*256 );
	};
};
} // namespace EFFLEGACY_MESH
namespace EFFLEGACY_PARTICLESYS {
struct PROPERTY_100
{
	//
	D3DXVECTOR3		m_vGVelocity;

	D3DXVECTOR3		m_vGGravityStart;
	D3DXVECTOR3		m_vGGravityEnd;

	DWORD			m_dwFlag;
	int				m_iCenterPoint;

	D3DXVECTOR3		m_vRange;
	float			m_fRangeRate;
	float			m_fRotateAngel;

	float			m_fRotateLAngel;

	float			m_fRotateLRate1;
	float			m_fRotateLRate2;

	float			m_fLengthStart;
	float			m_fLengthMid1;
	float			m_fLengthMid2;
	float			m_fLengthEnd;

	DWORD			m_uParticlesPerSec;

	char			m_szTexture[STRING_NUM_256];
	char			m_szMeshFile[STRING_NUM_256];

	//
	float			m_fTexRotateAngel;

	D3DXVECTOR4		m_vTexScale;

	float			m_fGravityStart;
	float			m_fGravityVar;
	float			m_fGravityEnd;

	float			m_fSizeStart;
	float			m_fSizeVar;
	float			m_fSizeEnd;

	float			m_fAlphaRate1;
	float			m_fAlphaRate2;

	float			m_fAlphaStart;
	float			m_fAlphaMid1;
	float			m_fAlphaMid2;
	float			m_fAlphaEnd;

	D3DXCOLOR		m_cColorStart;
	D3DXCOLOR		m_cColorVar;
	D3DXCOLOR		m_cColorEnd;

	float			m_fSpeed;
	float			m_fSpeedVar;

	float			m_fLife;
	float			m_fLifeVar;

	float			m_fTheta;

	int				m_nBlend;

	PROPERTY_100()
	{
		memset( m_szTexture, 0, sizeof(char)*STRING_NUM_256 );
		memset( m_szMeshFile, 0, sizeof(char)*STRING_NUM_256 );
	};
};
struct PROPERTY_101
{
	//
	D3DXVECTOR3		m_vGVelocity;

	D3DXVECTOR3		m_vGGravityStart;
	D3DXVECTOR3		m_vGGravityEnd;

	DWORD			m_dwFlag;
	int				m_iCenterPoint;

	D3DXVECTOR3		m_vRange;
	float			m_fRangeRate;
	float			m_fRotateAngel;

	float			m_fRotateLAngel;

	float			m_fRotateLRate1;
	float			m_fRotateLRate2;

	float			m_fLengthStart;
	float			m_fLengthMid1;
	float			m_fLengthMid2;
	float			m_fLengthEnd;

	DWORD			m_uParticlesPerSec;

	char			m_szTexture[STRING_NUM_256];
	char			m_szMeshFile[STRING_NUM_256];

	//
	D3DXVECTOR3		m_vWindDir;

	float			m_fTexRotateAngel;

	D3DXVECTOR4		m_vTexScale;

	float			m_fGravityStart;
	float			m_fGravityVar;
	float			m_fGravityEnd;

	float			m_fSizeStart;
	float			m_fSizeVar;
	float			m_fSizeEnd;

	float			m_fAlphaRate1;
	float			m_fAlphaRate2;

	float			m_fAlphaStart;
	float			m_fAlphaMid1;
	float			m_fAlphaMid2;
	float			m_fAlphaEnd;

	D3DXCOLOR		m_cColorStart;
	D3DXCOLOR		m_cColorVar;
	D3DXCOLOR		m_cColorEnd;

	float			m_fSpeed;
	float			m_fSpeedVar;

	float			m_fLife;
	float			m_fLifeVar;

	float			m_fTheta;

	int				m_nBlend;

	PROPERTY_101()
	{
		memset( m_szTexture, 0, sizeof(char)*STRING_NUM_256 );
		memset( m_szMeshFile, 0, sizeof(char)*STRING_NUM_256 );
	};
};
struct PROPERTY_102_103
{
	//
	D3DXVECTOR3		m_vGVelocity;

	D3DXVECTOR3		m_vGGravityStart;
	D3DXVECTOR3		m_vGGravityEnd;

	DWORD			m_dwFlag;
	int				m_iCenterPoint;

	D3DXVECTOR3		m_vRange;
	float			m_fRangeRate;
	float			m_fRotateAngel;

	float			m_fRotateLAngel;

	float			m_fRotateLRate1;
	float			m_fRotateLRate2;

	float			m_fLengthStart;
	float			m_fLengthMid1;
	float			m_fLengthMid2;
	float			m_fLengthEnd;

	DWORD			m_uParticlesPerSec;

	char			m_szTexture[STRING_NUM_256];
	char			m_szMeshFile[STRING_NUM_256];

	//
	D3DXVECTOR3		m_vWindDir;

	float			m_fTexRotateAngel;

	D3DXVECTOR4		m_vTexScale;

	float			m_fGravityStart;
	float			m_fGravityVar;
	float			m_fGravityEnd;

	float			m_fSizeStart;
	float			m_fSizeVar;
	float			m_fSizeEnd;

	float			m_fAlphaRate1;
	float			m_fAlphaRate2;

	float			m_fAlphaStart;
	float			m_fAlphaMid1;
	float			m_fAlphaMid2;
	float			m_fAlphaEnd;

	D3DXCOLOR		m_cColorStart;
	D3DXCOLOR		m_cColorVar;
	D3DXCOLOR		m_cColorEnd;

	float			m_fSpeed;
	float			m_fSpeedVar;

	float			m_fLife;
	float			m_fLifeVar;

	float			m_fTheta;

	int				m_nCol;
	int				m_nRow;
	float			m_fAniTime;

	int				m_nBlend;

	PROPERTY_102_103()
	{
		memset( m_szTexture, 0, sizeof(char)*STRING_NUM_256 );
		memset( m_szMeshFile, 0, sizeof(char)*STRING_NUM_256 );
	};
};
struct PROPERTY_104				// Ver.104
{
	//
	D3DXVECTOR3		m_vGVelocity;

	D3DXVECTOR3		m_vGGravityStart;
	D3DXVECTOR3		m_vGGravityEnd;

	DWORD			m_dwFlag;
	int				m_iCenterPoint;

	D3DXVECTOR3		m_vRange;
	float			m_fRangeRate;
	float			m_fRotateAngel;

	float			m_fRotateLAngel;

	float			m_fRotateLRate1;
	float			m_fRotateLRate2;

	float			m_fLengthStart;
	float			m_fLengthMid1;
	float			m_fLengthMid2;
	float			m_fLengthEnd;

	DWORD			m_uParticlesPerSec;

	char			m_szTexture[STRING_NUM_256];
	char			m_szMeshFile[STRING_NUM_256];

	//
	D3DXVECTOR3		m_vWindDir;

	float			m_fTexRotateAngel;

	D3DXVECTOR4		m_vTexScale;

	float			m_fGravityStart;
	float			m_fGravityVar;
	float			m_fGravityEnd;

	float			m_fSizeStart;
	float			m_fSizeVar;
	float			m_fSizeEnd;

	float			m_fAlphaRate1;
	float			m_fAlphaRate2;

	float			m_fAlphaStart;
	float			m_fAlphaMid1;
	float			m_fAlphaMid2;
	float			m_fAlphaEnd;

	D3DXCOLOR		m_cColorStart;
	D3DXCOLOR		m_cColorVar;
	D3DXCOLOR		m_cColorEnd;

	float			m_fSpeed;
	float			m_fSpeedVar;

	float			m_fLife;
	float			m_fLifeVar;

	float			m_fTheta;

	int				m_nCol;
	int				m_nRow;
	float			m_fAniTime;

	int				m_nBlend;
	int				m_nPower;

	PROPERTY_104()
	{
		memset( m_szTexture, 0, sizeof(char)*STRING_NUM_256 );
		memset( m_szMeshFile, 0, sizeof(char)*STRING_NUM_256 );
	};
};
struct PROPERTY_105				// Ver.105
{
	//
	D3DXVECTOR3		m_vGVelocity;
	D3DXVECTOR3		m_vGGravityStart;
	D3DXVECTOR3		m_vGGravityEnd;

	D3DXVECTOR2		m_vPlayTime;
	D3DXVECTOR2		m_vSleepTime;

	DWORD			m_dwFlag;
	int				m_iCenterPoint;

	D3DXVECTOR3		m_vRange;
	float			m_fRangeRate;
	float			m_fRotateAngel;

	float			m_fRotateLAngel;

	float			m_fRotateLRate1;
	float			m_fRotateLRate2;

	float			m_fLengthStart;
	float			m_fLengthMid1;
	float			m_fLengthMid2;
	float			m_fLengthEnd;

	DWORD			m_uParticlesPerSec;

	char			m_szTexture[STRING_NUM_256];
	char			m_szMeshFile[STRING_NUM_256];

	//
	D3DXVECTOR3		m_vWindDir;

	float			m_fTexRotateAngel;

	D3DXVECTOR4		m_vTexScale;

	float			m_fGravityStart;
	float			m_fGravityVar;
	float			m_fGravityEnd;

	float			m_fSizeStart;
	float			m_fSizeVar;
	float			m_fSizeEnd;

	float			m_fAlphaRate1;
	float			m_fAlphaRate2;

	float			m_fAlphaStart;
	float			m_fAlphaMid1;
	float			m_fAlphaMid2;
	float			m_fAlphaEnd;

	D3DXCOLOR		m_cColorStart;
	D3DXCOLOR		m_cColorVar;
	D3DXCOLOR		m_cColorEnd;

	float			m_fSpeed;
	float			m_fSpeedVar;

	float			m_fLife;
	float			m_fLifeVar;

	float			m_fTheta;

	int				m_nCol;
	int				m_nRow;
	float			m_fAniTime;

	int				m_nBlend;
	int				m_nPower;

	PROPERTY_105()
	{
		memset( m_szTexture, 0, sizeof(char)*STRING_NUM_256 );
		memset( m_szMeshFile, 0, sizeof(char)*STRING_NUM_256 );
	};
};
struct PROPERTY_106				// Ver.106
{
	//
	D3DXVECTOR3		m_vGVelocity;
	D3DXVECTOR3		m_vGGravityStart;
	D3DXVECTOR3		m_vGGravityEnd;

	D3DXVECTOR2		m_vPlayTime;
	D3DXVECTOR2		m_vSleepTime;

	DWORD			m_dwFlag;
	int				m_iCenterPoint;

	D3DXVECTOR3		m_vRange;
	float			m_fRangeRate;
	float			m_fRotateAngel;

	float			m_fRotateLAngel;

	float			m_fRotateLRate1;
	float			m_fRotateLRate2;

	float			m_fLengthStart;
	float			m_fLengthMid1;
	float			m_fLengthMid2;
	float			m_fLengthEnd;

	DWORD			m_uParticlesPerSec;

	char			m_szTexture[STRING_NUM_256];
	char			m_szMeshFile[STRING_NUM_256];
	char			m_szEffFile[STRING_NUM_256];

	//
	D3DXVECTOR3		m_vWindDir;

	float			m_fTexRotateAngel;

	D3DXVECTOR4		m_vTexScale;

	float			m_fGravityStart;
	float			m_fGravityVar;
	float			m_fGravityEnd;

	float			m_fSizeStart;
	float			m_fSizeVar;
	float			m_fSizeEnd;

	float			m_fAlphaRate1;
	float			m_fAlphaRate2;

	float			m_fAlphaStart;
	float			m_fAlphaMid1;
	float			m_fAlphaMid2;
	float			m_fAlphaEnd;

	D3DXCOLOR		m_cColorStart;
	D3DXCOLOR		m_cColorVar;
	D3DXCOLOR		m_cColorEnd;

	float			m_fSpeed;
	float			m_fSpeedVar;

	float			m_fLife;
	float			m_fLifeVar;

	float			m_fTheta;

	int				m_nCol;
	int				m_nRow;
	float			m_fAniTime;

	int				m_nBlend;
	int				m_nPower;

	PROPERTY_106()
	{
		memset( m_szTexture, 0, sizeof(char)*STRING_NUM_256 );
		memset( m_szMeshFile, 0, sizeof(char)*STRING_NUM_256 );
		memset( m_szEffFile, 0, sizeof(char)*STRING_NUM_256 );
	};
};
} // namespace EFFLEGACY_PARTICLESYS
