'use strict';
//
// Emit C# accessors for the measured packet structs.
//
//   node gen-csharp.js --out ../../unity/com.ran.mobile.assets/Runtime/RanPackets.cs
//
// The Unity client has to read the same wire format the Node client already
// reads, and the offsets for both come from the same place: `layout.json`,
// measured by MSVC over the real headers. Writing them a second time by hand in
// C# would be a copy with no way to stay honest — the exact failure this project
// has hit before with texture names and node type ids.
//
// **Accessors, not structs.** A C# `struct` with `[StructLayout(Sequential)]`
// looks like the obvious mapping and is wrong here: the shipped layout includes
// MSVC's padding decisions, and .NET is free to lay out differently. Reading at
// a measured offset out of a byte[] is exactly what the Node client does, is
// endian-explicit, and cannot silently disagree with the probe.
//
// Only structs reachable from the message set the client actually handles are
// emitted; 521 measured structs would otherwise become an unreadable file.
const fs = require('fs');
const path = require('path');

const L = JSON.parse(fs.readFileSync(path.join(__dirname, 'layout.json'), 'utf8'));
const A = L.allStructs || {};

// The Phase 0 + Tier-1 message set: login handshake, character list and select,
// field entry, movement, and the player's own state. Everything else is decoded
// on demand and does not need generated accessors yet.
const WANTED = [
  'NET_CLIENT_VERSION',
  'NET_LOGIN_FEEDBACK_DATA',
  'NET_ENCRYPT_KEY',
  'GLMSG::SNETPC_UPDATE_STATE',
  'GLMSG::SNETPC_UPDATE_STATE_BRD',
  'GLMSG::SNETPC_HP_CHECK',
  'GLMSG::SNETDROP_CROW',
  'GLMSG::SNETCROW_DAMAGE',
  'GLMSG::SNETCROW_MOVETO',
  'GLMSG::SNETPC_GOTO',
  'GLMSG::SNETLOBBY_CHARJOIN',
  'SDROP_CROW',
];

const csName = (n) => n.replace(/^GLMSG::/, '').replace(/[^A-Za-z0-9_]/g, '_');

/**
 * Pick a reader for a field from its MEASURED SIZE.
 *
 * Size is all the probe records, so a 4-byte field could be int, uint or float.
 * Emitting every plausible reader and letting the caller pick is safer than
 * guessing one: a wrong guess is silent, an absent accessor is a compile error.
 */
function accessors(struct, name, f) {
  const out = [];
  const at = `Base + ${f.off}`;
  const doc = `        /// <summary>Offset ${f.off}, ${f.size} bytes (measured).</summary>`;
  if (f.size === 1) {
    out.push(doc, `        public byte ${name} => data[${at}];`);
  } else if (f.size === 2) {
    out.push(doc, `        public ushort ${name} => BitConverter.ToUInt16(data, ${at});`);
  } else if (f.size === 4) {
    out.push(doc,
      `        public uint ${name} => BitConverter.ToUInt32(data, ${at});`,
      `        public int ${name}_i32 => BitConverter.ToInt32(data, ${at});`,
      `        public float ${name}_f32 => BitConverter.ToSingle(data, ${at});`);
  } else if (f.size === 8) {
    // Two dwords. GLDWDATA is (current, max) — GLAnySummon.h:141 builds one as
    // GLDWDATA(GETHP(), GETMAXHP()) — so both halves are exposed by name.
    out.push(doc,
      `        public uint ${name}_lo => BitConverter.ToUInt32(data, ${at});`,
      `        public uint ${name}_hi => BitConverter.ToUInt32(data, ${at} + 4);`);
  } else if (f.size === 12) {
    out.push(doc,
      `        public Vector3 ${name} => new Vector3(` +
      `BitConverter.ToSingle(data, ${at}), BitConverter.ToSingle(data, ${at} + 4), ` +
      `BitConverter.ToSingle(data, ${at} + 8));`);
  } else if (f.size > 12) {
    // Char arrays. Decoded latin-1 by hand: the shipped text is CP949 and
    // Encoding.Latin1 does not exist in netstandard2.1, which Unity targets.
    out.push(doc,
      `        public string ${name} => RanPackets.Str(data, ${at}, ${f.size});`);
  }
  return out;
}

const parts = [];
parts.push(`// GENERATED by MOBILE/tools/layout-probe/gen-csharp.js -- do not edit.
//
// Offsets and sizes are MEASURED by MSVC over the real headers and shared with
// the Node client through layout.json. Nothing here is hand-written, which is
// the point: a second hand-maintained copy of a wire format is a copy that
// silently drifts.
//
// Accessors read out of a byte[] at a measured offset rather than mapping a
// [StructLayout] struct, because the shipped layout embeds MSVC's padding and
// .NET is free to choose its own.
using System;
using UnityEngine;

namespace Ran.Mobile.Assets
{
    public static class RanPackets
    {
        /// <summary>Fixed-width char field, NUL-terminated, decoded latin-1.</summary>
        public static string Str(byte[] data, int at, int max)
        {
            if (data == null || at < 0 || at >= data.Length) return string.Empty;
            int end = Math.Min(at + max, data.Length);
            int n = at;
            while (n < end && data[n] != 0) n++;
            var chars = new char[n - at];
            // Byte-for-byte to char: Encoding.Latin1 is .NET 5+, and Unity's
            // netstandard2.1 profile does not have it. The text is CP949 and
            // needs a second decode pass to display; this preserves the bytes.
            for (int i = 0; i < chars.Length; i++) chars[i] = (char)data[at + i];
            return new string(chars);
        }
    }
`);

let emitted = 0, missing = [];
for (const key of WANTED) {
  const s = A[key];
  if (!s) { missing.push(key); continue; }
  const name = csName(key);
  parts.push(`
    /// <summary>
    /// <c>${key}</c> — ${s.size} bytes, ${Object.keys(s.fields).length} fields.
    /// </summary>
    public readonly struct ${name}
    {
        public const int Size = ${s.size};
        private readonly byte[] data;
        private readonly int Base;
        public ${name}(byte[] data, int offset = 0) { this.data = data; this.Base = offset; }
        public bool Fits => data != null && Base + Size <= data.Length;
`);
  for (const [fname, f] of Object.entries(s.fields)) {
    const lines = accessors(key, fname, f);
    if (lines.length) parts.push(lines.join('\n'));
  }
  parts.push('    }');
  emitted++;
}
parts.push('}');

const outArg = process.argv.indexOf('--out');
const text = parts.join('\n') + '\n';
if (outArg > 0) {
  const p = path.resolve(__dirname, process.argv[outArg + 1]);
  fs.writeFileSync(p, text);
  console.log(`wrote ${path.basename(p)} — ${emitted} structs, ${text.split('\n').length} lines`);
} else {
  console.log(`${emitted} structs would be emitted, ${text.split('\n').length} lines`);
}
if (missing.length) console.log(`NOT in layout.json: ${missing.join(', ')}`);
