set(Lib_Client_SOURCES
  ${RAN_SRC}/Lib_Client/ClientApex.cpp
  ${RAN_SRC}/Lib_Client/DbActionLogic.cpp
  ${RAN_SRC}/Lib_Client/DbActionLogicClub.cpp
  ${RAN_SRC}/Lib_Client/DbActionLogicEquipmentLock.cpp
  ${RAN_SRC}/Lib_Client/DbActionLogicInventoryLock.cpp
  ${RAN_SRC}/Lib_Client/DbActionLogicLog.cpp
  ${RAN_SRC}/Lib_Client/DbActionLogicPet.cpp
  ${RAN_SRC}/Lib_Client/DbActionLogicShop.cpp
  ${RAN_SRC}/Lib_Client/DbActionLogicSMS.cpp
  ${RAN_SRC}/Lib_Client/DbActionLogicStorageLock.cpp
  ${RAN_SRC}/Lib_Client/DbActionLogicVehicle.cpp
  ${RAN_SRC}/Lib_Client/DxCharSham.cpp
  ${RAN_SRC}/Lib_Client/DxGameStage.cpp
  ${RAN_SRC}/Lib_Client/DxGlobalStage.cpp
  ${RAN_SRC}/Lib_Client/dxincommand.cpp
  ${RAN_SRC}/Lib_Client/DxLobyStage.cpp
  ${RAN_SRC}/Lib_Client/DxLobyStageCreateChar.cpp
  ${RAN_SRC}/Lib_Client/DxLobyStageSelectChar.cpp
  ${RAN_SRC}/Lib_Client/DxParamSet.cpp
  ${RAN_SRC}/Lib_Client/DxServerInstance.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/Emoticon.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLActivity.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLActivityData.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLActivityDefine.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLAgentServer.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLAgentServerEx.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLAgentServerMsg.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLAGLandMan.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLAnyPet.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLAnySummon.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLAnySummonMsg.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLARoundSlot.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLAutoLevel.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLAutoLevelMan.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLBusData.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLBusList.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLBusStation.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLChar.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLCharacter.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLCharacterAllianceMsg.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLCharacterClubBattleMsg.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLCharacterClubMsg.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLCharacterConfrontMsg.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLCharacterMiniGameMsg.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLCharacterMsg.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLCharacterQuestMsg.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLCharacterSkill.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLCharacterSkillTarget.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLCharActivity.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLCharactorReq.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLCharactorReq2.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLCharAG.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLCharAGClub.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLCharClient.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLCharClubMsg.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLCharCodex.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLCharData.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLCharDataActivity.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLCharDataCodex.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLCharDataLoad.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLCharDataPandora.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLCharDefine.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLCharEx.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLCharInvenMsg.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLCharInvenMsg2.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLCharMsg.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLCharPetMsg.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLCharPMarketMsg.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLCharQuest.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLCharQuestMsg.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLCharSkillMsg.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLCharSkillMsg_SetTarget.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLCharStorageMsg.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLClubDeathMatch.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLClubMan.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLCodex.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLCodexData.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLCodexDefine.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLCommentFile.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLContrlMsg.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLContrlPcMsg.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLCrow.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLCrowClient.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLCrowData.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLCrowDataAction.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLCrowDataAttack.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLCrowDataBasic.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLCrowDataGen.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLCrowDataItemExchange.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLCrowDataLoad.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLCrowDataNPCShop.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLCrowGenerateReward.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLCrowReAction.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLCrowRenList.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLCrowSkill.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLCrowSkillTarget.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLDescriptionFile.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLEventProc.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLFactData.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLFactEffect.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLFreePK.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLFriendClient.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLGaeaClient.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLGaeaServer.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLGaeaServerEx.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLGaeaServerMsg.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLGuidance.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLInventory.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLItem.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLItemBasic.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLItemBox.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLItemDef.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLItemDef2.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLItemDrug.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLItemGenerate.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLItemGrinding.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLItemLink.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLITEMLMT.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLItemMan.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLItemMix.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLItemMixMan.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLItemPet.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLItemPetSkin.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLItemQuestion.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLItemRandomBox.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLItemRandomOption.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLItemRVCard.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLItemSelfBuff.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLItemSkillBook.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLItemSuit.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLItemVehicle.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLLandMan.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLLandManClient.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLLandManSet.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLLandMark.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLLevelEtcFunction.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLLevelFile.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLLevelFileSaveLoad.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLLevelHead.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLLevelRequire.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLMapAxisInfo.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLMapList.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLMapNode.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLMaterial.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLMaterialClient.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLMobSchedule.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLMobScheduleSaveLoad.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLMoney.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLNote.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLogicData.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLogicDataLoad.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLogicEx.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLogicExNPC.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLogixExPC.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLParty.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLPartyClient.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLPartyField.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLPartyFieldMan.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLPartyMan.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLPet.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLPetClient.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLPetClientMsg.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLPetClientReq.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLPetClientSkill.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLPetField.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLPetFieldMsg.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLPrivateMarket.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLProductDefine.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLPVPCaptureTheFlag.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLPVPCaptureTheFlagAgent.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLPVPCaptureTheFlagAgentMapMove.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLPVPCaptureTheFlagAgentMsg.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLPVPCaptureTheFlagAgentRegister.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLPVPCaptureTheFlagClient.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLPVPCaptureTheFlagClientFlag.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLPVPCaptureTheFlagClientMSG.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLPVPCaptureTheFlagField.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLPVPCaptureTheFlagFieldFlag.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLPVPCaptureTheFlagFieldMSG.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLPVPCaptureTheFlagFieldRanking.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLPVPSchoolWars.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLPVPSchoolWarsAgent.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLPVPSchoolWarsAgentMapMove.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLPVPSchoolWarsAgentMsg.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLPVPSchoolWarsAgentRegister.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLPVPSchoolWarsClient.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLPVPSchoolWarsClientMSG.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLPVPSchoolWarsField.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLPVPSchoolWarsFieldMSG.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLPVPSchoolWarsFieldRanking.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLTournament.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLPVPTyranny.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLPVPTyrannyAgent.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLPVPTyrannyAgentMapMove.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLPVPTyrannyAgentMSG.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLPVPTyrannyAgentRegister.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLPVPTyrannyAgentTower.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLPVPTyrannyClient.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLPVPTyrannyClientMSG.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLPVPTyrannyField.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLPVPTyrannyFieldMSG.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLPVPTyrannyFieldRanking.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLQuest.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLQuestGenItem.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLQuestMan.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLQuestPlay.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLQuestStart.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLQuestStep.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLSchoolFreePK.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLSkill.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLSkillApply.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLSkillBasic.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLSkillDefine.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLSkillExData.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLSkillLearn.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLSkillSpecial.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLSkillToolTip.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLStrikeSelector.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLStringTable.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLSummon.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLSummonClient.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLSummonClientMsg.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLSummonData.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLSummonDef.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLSummonField.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLSummonFieldMsg.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLSummonSkill.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLTaxiData.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLTaxiStation.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLTrade.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLTradeClient.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/GLVEHICLE.cpp
  ${RAN_SRC}/Lib_Client/G-Logic/stl_Func.cpp
  ${RAN_SRC}/Lib_Client/NpcTalk/NpcDialogue.cpp
  ${RAN_SRC}/Lib_Client/NpcTalk/NpcDialogueCase.cpp
  ${RAN_SRC}/Lib_Client/NpcTalk/NpcDialogueSet.cpp
  ${RAN_SRC}/Lib_Client/NpcTalk/NpcTalk.cpp
  ${RAN_SRC}/Lib_Client/NpcTalk/NpcTalkCondition.cpp
  ${RAN_SRC}/Lib_Client/NpcTalk/NpcTalkControl.cpp
)
